## Write a Numpy program to compute the multiplication of two given matrixes

In [1]:
import numpy as np

m1 = ([1,6,5],
      [3,4,8],
      [2,12,3])

m2 = ([3,4,6],
      [5,6,7],
      [6,56,7])

In [2]:
np.dot(m1,m2)

array([[ 63, 320,  83],
       [ 77, 484, 102],
       [ 84, 248, 117]])

## Write a NumPy program to compute the determinant of a given square array

In [3]:
np.linalg.det(m1)

98.00000000000004

In [4]:
np.linalg.det(m2)

441.9999999999995

## Write a NumPy program to compute the cross product of two given vectors

In [5]:
np.cross(m1,m2)

array([[ 16,   9, -14],
       [-20,  19,  -2],
       [-84,   4,  40]])

## Write a NumPy program to compute the condition number of a given matrix

In [6]:
np.linalg.cond(m1)

17.078964945002536

In [7]:
np.linalg.cond(m2)

70.70705233085806

## Write a NumPy program to compute the inverse of a given matrix

In [8]:
np.linalg.inv(m1)

array([[-0.85714286,  0.42857143,  0.28571429],
       [ 0.07142857, -0.07142857,  0.07142857],
       [ 0.28571429,  0.        , -0.14285714]])

In [9]:
np.linalg.inv(m2)

array([[-0.7918552 ,  0.69683258, -0.01809955],
       [ 0.0158371 , -0.03393665,  0.02036199],
       [ 0.5520362 , -0.32579186, -0.00452489]])